// lib/theme.js
export const midnight = {
  // palette
  bg: '#0b0b0f',
  text: '#e5e7eb',
  cardBg: '#0f172a',
  cardBorder: '#1f2937',
  fieldBg: '#111827',
  fieldBorder: '#334155',
  accentBorder: '#38bdf8', // sky-400
  accentBg: '#0ea5e9',     // sky-500
  muted: '#9ca3af',
  subtle: '#6b7280',
};

export const ui = {
  page: {
    minHeight: '100vh',
    background: midnight.bg,
    color: midnight.text,
    fontFamily: 'ui-sans-serif',
    padding: '32px 16px',
  },
  wrap: (max = 1040) => ({ maxWidth: max, margin: '0 auto' }),
  header: { textAlign: 'center', marginBottom: 18 },
  title: { fontSize: 36, fontWeight: 800, letterSpacing: '-0.02em' },
  card: {
    background: midnight.cardBg,
    border: `1px solid ${midnight.cardBorder}`,
    borderRadius: 16,
    padding: 20,
    maxWidth: '100%',
    overflow: 'hidden',
  },
  sectionGrid: { display: 'grid', gap: 16, gridTemplateColumns: '1fr' },
  label: { fontSize: 13, color: midnight.muted, marginBottom: 6, display: 'block' },
  row: { display: 'flex', gap: 8, flexWrap: 'wrap' },
  input: {
    display: 'block',
    width: '100%',
    maxWidth: '100%',
    minWidth: 0,
    boxSizing: 'border-box',
    padding: '12px 14px',
    borderRadius: 12,
    border: `1px solid ${midnight.fieldBorder}`,
    background: midnight.fieldBg,
    color: midnight.text,
    outline: 'none',
  },
  btnPrimary: {
    padding: '12px 16px',
    borderRadius: 12,
    border: `1px solid ${midnight.accentBorder}`,
    background: midnight.accentBg,
    color: midnight.bg,
    textDecoration: 'none',
    fontWeight: 700,
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  btnSecondary: {
    padding: '10px 14px',
    borderRadius: 10,
    border: `1px solid ${midnight.fieldBorder}`,
    background: midnight.fieldBg,
    color: midnight.text,
    textDecoration: 'none',
    fontWeight: 600,
    boxSizing: 'border-box',
  },
  muted: { color: midnight.muted },
  subtle: { color: midnight.subtle, fontSize: 13 },
  tabs: { display: 'flex', gap: 8, marginBottom: 12, flexWrap: 'wrap' },
  tab: (active) => ({
    flex: 1,
    textAlign: 'center',
    padding: '10px 12px',
    borderRadius: 10,
    cursor: 'pointer',
    fontWeight: 700,
    border: active ? `1px solid ${midnight.accentBorder}` : `1px solid ${midnight.fieldBorder}`,
    background: active ? midnight.accentBg : midnight.fieldBg,
    color: active ? midnight.bg : midnight.text,
    boxSizing: 'border-box',
    minWidth: 120,
  }),
};
